version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/gym_assets.db
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-change-in-production}
      - API_KEY=${API_KEY:-gym-api-key-123}
    volumes:
      - ./data:/app/data
      - ./api:/app/api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add a simple web UI for testing
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/openapi.json
      - BASE_URL=/docs
    depends_on:
      - api